# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3a9566b6bfa8fbf55276008b8a283384d52bb8885fce97e63eea8ef85a5c491466eb734dad92111b66ad5b3fe22e62824c981a674fad414c920d7ebd16e3a7b

test:
  secret_key_base: 6860367a3b9e2d20ecc33dafbe2334d16556f10d2883df5bd6608731f93dcd567de31228051ecd69696047405e46ba897f222ad92b67905ddeedb6f749889786

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
